steps:
  docker:
    image: woodpeckerci/plugin-docker-buildx:2
    settings:
      platforms: linux/arm64,linux/amd64
      repo: codeberg.org/hyperpipe/hyperpipe-backend
      registry: codeberg.org
      tags: latest
      username: snematoda
      password:
        from_secret: cb_token
    when:
      branch: main
      event: ['push']